# Generated by Django 3.0.5 on 2023-06-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230627_1723'),
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='category',
            name='expire_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
